### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by ghost** [RawToast/Anki-Retirement-Addon#1]
Hey! I'm getting this error when opening anki from scratch and sometimes once I enter a profile.
I've the Migaku Retirement addon disabled but it happens nonetheless.

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.45 (355e66e8) Python 3.9.6 Qt 5.15.2 PyQt 5.15.4
Platform: Linux
Flags: frz=False ao=True sv=2
Add-ons, last update check: 2021-08-02 09:25:18
Add-ons possibly involved: ⁨Card Retirement⁩

Caught exception:
Traceback (most recent call last):
  File "/home/yannicko/.local/lib/python3.9/site-packages/aqt/main.py", line 300, in onOpenProfile
    self.loadProfile(self.profileDiag.closeWithoutQuitting)
  File "/home/yannicko/.local/lib/python3.9/site-packages/aqt/main.py", line 425, in loadProfile
    gui_hooks.profile_did_open()
  File "/home/yannicko/.local/lib/python3.9/site-packages/aqt/hooks_gen.py", line 2913, in __call__
    anki.hooks.runHook("profileLoaded")
  File "/home/yannicko/.local/lib/python3.9/site-packages/anki/hooks.py", line 34, in runHook
    func(*args)
  File "/home/yannicko/.local/share/Anki2/addons21/1972853015/main.py", line 27, in attemptStartingRefresh
    startingRefresh()
  File "/home/yannicko/.local/share/Anki2/addons21/1972853015/main.py", line 32, in startingRefresh
    applyRetirementActions()
  File "/home/yannicko/.local/share/Anki2/addons21/1972853015/main.py", line 208, in applyRetirementActions
    displayNotification('<b>'+ str(total) + ' card(s) have been retired in ' + str(round(timeEnd - timeStart, 3)) + ' seconds:</b><br>' + notification)
  File "/home/yannicko/.local/share/Anki2/addons21/1972853015/main.py", line 250, in displayNotification
    showInfo(text ,False,"", "info", "Card Retirement")
  File "/home/yannicko/.local/lib/python3.9/site-packages/aqt/utils.py", line 131, in showInfo
    mb = QMessageBox(parent_widget)  #
TypeError: arguments did not match any overloaded call:
  QMessageBox(parent: QWidget = None): argument 1 has unexpected type 'bool'
  QMessageBox(QMessageBox.Icon, str, str, buttons: Union[QMessageBox.StandardButtons, QMessageBox.StandardButton] = QMessageBox.NoButton, parent: QWidget = None, flags: Union[Qt.WindowFlags, Qt.WindowType] = Qt.Dialog|Qt.MSWindowsFixedSizeDialogHint): not enough arguments
```

**Comment by RawToast** [comment]
Thanks! Looks like the types used for showInfo have changed too.

If you're willing to do an experiment for me: open `/home/yannicko/.local/share/Anki2/addons21/1972853015/main.py` and go to line 249-250, which should be:

```python
def displayNotification(text):
    showInfo(text ,False,"", "info", "Card Retirement")
```

And change the second line to: `showInfo(text ,"", "info", "Card Retirement")`   I think that should fix it. If you can confirm that works, I'll tidy it up and release a new version.

**Comment by RawToast** [comment]
Managed to replicate this to test, I've just pushed a new version to Ankiweb.
